				</TD>
			</TR>
			<TR BGCOLOR="#000099">
				<TD VALIGN="top">
					<P CLASS="nav">
						&copy;&nbsp;2022, 
						<A CLASS="nav" HREF="http://ssmp.health.kiev.ua/index.php">
							<?php echo $la_1 ?> <!--назва-->
						</A>
					</P>
				</TD>
				<TD ALIGN="right" VALIGN="top">
					<P CLASS="nav">
							<?php echo $la_62 ?> <!--"Реєстрація дійсна до закриття вікна чи переходу за посиланням "-->
						<A CLASS="nav" HREF="login.php">
							<?php echo $la_63 ?> <!--"Вихід"-->
						</A>
					</P>
				</TD>
			</TR>
		</TABLE>
	</BODY>
</HTML>