<!--
	header1.inc
	Верхнє меню
-->
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<HTML>
<HEAD>
	<META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=windows-1251">
	<TITLE>
		phone/admin : 
		<?php echo $title ?>
	</TITLE>
	<LINK REL=stylesheet HREF="../style.css" TYPE="text/css">
</HEAD>
<BODY BGCOLOR="#FFFFFF">
<TABLE BORDER="0" CELLSPACING="0" CELLPADDING="4" WIDTH="100%">
<TR BGCOLOR="#000099">
	<TD WIDTH="30%" VALIGN="top">
		<P CLASS="nav">
			<A CLASS="nav" HREF="../index.php"> 
				<?php echo $la_149_5; ?> 
			</A><!--"До довідника"-->
		</P>
	</TD>
	<TD WIDTH="70%" ALIGN="right" VALIGN="top">
		<P CLASS="nav">
			<?php echo $la_149_6 ?>
		</P><!--Для Адміну-->
		<P CLASS="big">
			<?php echo $la_155_1 ?>
			<BR>
			<?php echo $title ?>
		</P <!--Телефонний довідник:--> 
	</TD>
</TR>
<TR>
<TD COLSPAN="2">
